#!/bin/bash

PLATFORM_LABEL=x86_64-linux-gnu

GSTREAMER_LOCATION_PATH=/usr/local/gstreamer-1.18.6

LD_LIBRARY_PATH=$GSTREAMER_LOCATION_PATH/lib/$PLATFORM_LABEL
GST_PLUGIN_PATH=$GSTREAMER_LOCATION_PATH/lib/$PLATFORM_LABEL/gstreamer-1.0
GST_PLUGIN_SCANNER=$GSTREAMER_LOCATION_PATH/libexec/gstreamer-1.0/gst-plugin-scanner
GST_PLUGIN_SYSTEM_PATH=
GST_REGISTRY=$HOME/registry.dat
PKG_CONFIG_PATH=$GSTREAMER_LOCATION_PATH/lib/$PLATFORM_LABEL/pkgconfig


export LD_LIBRARY_PATH GST_PLUGIN_PATH GST_PLUGIN_SCANNER GST_PLUGIN_SYSTEM_PATH GST_REGISTRY PKG_CONFIG_PATH



