#!/bin/bash

#PATH=/opt/python/3.13.1/bin:$PATH
#export PATH


GSTREAMER_LOCATION_PATH=/usr/local/gstreamer-1.24.10

LD_LIBRARY_PATH=$GSTREAMER_LOCATION_PATH/lib/aarch64-linux-gnu
GST_PLUGIN_PATH=$GSTREAMER_LOCATION_PATH/lib/aarch64-linux-gnu/gstreamer-1.0
GST_PLUGIN_SCANNER=$GSTREAMER_LOCATION_PATH/libexec/gstreamer-1.0/gst-plugin-scanner
GST_PLUGIN_SYSTEM_PATH=
GST_REGISTRY=$GSTREAMER_LOCATION_PATH/registry.dat
PKG_CONFIG_PATH=$GSTREAMER_LOCATION_PATH/lib/aarch64-linux-gnu/pkgconfig

export LD_LIBRARY_PATH GST_PLUGIN_PATH GST_PLUGIN_SCANNER GST_PLUGIN_SYSTEM_PATH GST_REGISTRY PKG_CONFIG_PATH
